Update sorted_json.rs
We're taking f64, floating point value. Updating the same at the required place.
failures:

---- sorted_json::tests::to_json stdout ----
thread 'sorted_json::tests::to_json' panicked at 'assertion failed: `(left == right)`
  left: `"1.0"`